Rework whitepaper
AshAvalanche/ash-docs pull request #10
Opened 2023-02-25 17:15 UTC by Nuttymoon

### Linked issues

- Fixes #9

### Dependencies

- https://github.com/AshAvalanche/ash-docs/pull/8

### Changes

- _(whitepaper)_ Update with the latest reflections, add missing links, add glossary links

2023-02-25 17:43 UTC, lToinou approved these changes

2023-02-26 17:22 UTC, leopaul36 requested changes

2023-02-26 17:22 UTC, leopaul36 commented on docs/protocol/ash-for-subnet-owners/overview.md
> +- Spontaneous validation by the protocol
```suggestion
- Voted validation by the protocol
```

2023-02-26 18:38 UTC, leopaul36 approved these changes

2023-02-26 18:44 UTC, merged