feat: add Console local network guide
AshAvalanche/ash-docs pull request #70
Opened 2023-11-23 16:50 UTC by leopaul36

### Linked issues

- Fix #69 

### Changes

- Add Avalanche Local network guide

### Additional comments

- Prerequisites, Cloud credential setup and project setup are duplicated from the Avalanche Fuji node guide

2023-11-24 11:41 UTC, Nuttymoon requested changes

2023-11-24 11:41 UTC, Nuttymoon commented on docs/console/guides/fuji-node/avalanche-node.md
> +1. Gather the node ID secret ID and cloud region secret ID from the previous steps.
```suggestion
1. Gather the node ID secret ID and cloud region ID from the previous steps.
```

2023-11-24 11:41 UTC, Nuttymoon commented on docs/console/guides/local-network/index.md
> +# Avalanche local network
```suggestion
# Avalanche Devnet (Local Network)
```

2023-11-24 11:41 UTC, Nuttymoon commented on docs/console/guides/local-network/index.md
> +This guide will walk you through setting up an 5-node Avalanche [local](https://docs.avax.network/nodes/configure/avalanchego-config-flags#network-id) network with the Ash Console.
```suggestion
This guide will walk you through setting up a 5-node Avalanche devnet ([local network](https://docs.avax.network/nodes/configure/avalanchego-config-flags#network-id) network) with the Ash Console.

Devnets allow you to develop your Subnet out of sight in an environment where you have full control!

:::info
Devnets use the `local` network setup with hardcoded validator nodes and airdrop address.
:::
```

2023-11-24 11:41 UTC, Nuttymoon commented on docs/console/guides/local-network/node-ids.md
> +Node IDs are stored as a [secret](/docs/console/glossary#secret) in the Console.
```suggestion
Node IDs are stored as [secrets](/docs/console/glossary#secret) in the Console.
```

2023-11-24 11:41 UTC, Nuttymoon commented on docs/console/guides/local-network/node-ids.md
> +   cd ash-console-guides/local-network
```suggestion
   mkdir -p ash-console-guides/devnet-network
   cd ash-console-guides/devnet-network
```

2023-11-24 11:41 UTC, Nuttymoon commented on docs/console/guides/local-network/node-ids.md
> +In this part of the guide, we will create **5 node ID secrets** for the 5 nodes of our local Avalanche network.
```suggestion
In this part of the guide, we will create **5 node ID secrets** for the 5 nodes of our Avalanche devnet.
```

2023-11-24 11:41 UTC, Nuttymoon commented on docs/console/guides/local-network/node-ids.md
> +The ["Local Test Network Creation"](/docs/toolkit/ansible-avalanche-collection/tutorials/local-test-network) tutorial uses the same certificates for the 5 nodes of the local network. In this step, we
```suggestion
The [Local Test Network Creation tutorial](/docs/toolkit/ansible-avalanche-collection/tutorials/local-test-network) uses the same certificates and keys for the 5 validator nodes. Let's fetch the certificate and key files from the [`ansible-avalanche-getting-started`](https://github.com/AshAvalanche/ansible-avalanche-getting-started) repository.
```

2023-11-24 11:41 UTC, Nuttymoon commented on docs/console/guides/local-network/node-ids.md
> +2. Fetch the local nodes certificates from the [`ansible-avalanche-getting-started`](https://github.com/AshAvalanche/ansible-avalanche-getting-started/tree/main/files/staking) repository:
```suggestion
2. Fetch the local nodes certificates and keys from the [`ansible-avalanche-getting-started`](https://github.com/AshAvalanche/ansible-avalanche-getting-started/tree/main/files/staking) repository:
```

2023-11-24 11:41 UTC, Nuttymoon commented on docs/console/guides/local-network/project-region.md
> +```
Suggestion: ~`local-network`~ `devnet`
```bash title="Command"
ash console project create '{"name": "devnet-guide", "network": "local"}'
```

```bash title="Output"
Project created successfully!
+--------------------------------------+-------------+--------------+---------+---------------+------------------+
| Project ID                           | Owner ID    | Name         | Network | Cloud regions | Created at       |
+======================================+=============+=====================+=========+===============+==================+
| 70228a47-5ab1-493b-b921-5c22b83bfbf7 | fce8...3695 | devnet-guide | Local   |               | 2023-11-23T15:08 |
+--------------------------------------+-------------+--------------+---------+---------------+------------------+

Switched to project 'devnet-guide' (70228a47-5ab1-493b-b921-5c22b83bfbf7)!
```

2023-11-24 11:41 UTC, Nuttymoon commented on docs/toolkit/ansible-avalanche-collection/tutorials/vm-management-custom.md
I think you commited this file by error.

2023-11-28 10:06 UTC, leopaul36 commented on docs/toolkit/ansible-avalanche-collection/tutorials/vm-management-custom.md
Removed

2023-11-28 14:10 UTC, merged