feat(console): update docs for blueprints
AshAvalanche/ash-docs pull request #77
Opened 2023-12-21 15:18 UTC by Nuttymoon

### Dependencies

- https://github.com/AshAvalanche/jeeo/pull/109
- https://github.com/AshAvalanche/ash-rs/pull/79

### Changes

- Console docs
  - Add the `Console Blueprint` page in the reference section
  - Updates the reference pages + guides to reflect the latest CLI changes, esp. YAML support + blueprints

2023-12-21 16:56 UTC, leopaul36 commented on docs/console/reference/blueprints.md
> +Applyin a blueprint is as simple as running the `blueprint apply` command and providing the blueprint path:
```suggestion
Applying a blueprint is as simple as running the `blueprint apply` command and providing the blueprint path:
```

2023-12-21 17:15 UTC, leopaul36 commented on docs/console/guides/local-network/node-ids.md
> +We will use the [local-node-ids.yaml blueprint](https://github.com/AshAvalanche/ash-rs/blob/ash-console-alpha/crates/ash_cli/examples/console/blueprint/local-node-ids.yaml) to create the node ID secr
```suggestion
We will use the [local-node-ids.yaml](https://github.com/AshAvalanche/ash-rs/blob/ash-console-alpha/crates/ash_cli/examples/console/blueprint/local-node-ids.yaml) blueprint to create the node ID secrets for the 5 nodes of our Avalanche devnet.
```

2023-12-21 17:36 UTC, leopaul36 commented on docs/console/guides/local-network/avalanche-nodes.md
> +It is common that **resources of the same type share some configuration**. For example, all the Avalanche nodes of our devnet will have the **same AvalancheGo version**.
```suggestion
It is common that **resources of the same project share some configuration**. For example, all the Avalanche nodes of our devnet will have the **same AvalancheGo version**.
```

2023-12-22 10:45 UTC, leopaul36 approved these changes

2023-12-27 17:02 UTC, leopaul36 commented on docs/console/guides/local-network/avalanche-nodes.md
>  - The above command takes about ~30 seconds to complete.
Closer to a minute

2024-01-02 10:24 UTC, Nuttymoon commented on docs/console/guides/local-network/avalanche-nodes.md
>  - The above command takes about ~30 seconds to complete.
```suggestion
- The above command takes about 1 minute to complete.
```

2024-01-02 18:34 UTC, leopaul36 requested changes

2024-01-02 18:34 UTC, leopaul36 commented on docs/console/guides/blueprint/blueprint-configuration.md
> +Enter `y` and watch the magic happen!
I think we should also copy the section from `/docs/console/guides/local-network/avalanche-nodes#health`

2024-01-03 17:15 UTC, merged